LTO_ENABLE = yes            # Link Time Optimization enabled
# BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
# EXTRAKEY_ENABLE = yes        # Audio control and System control
# CONSOLE_ENABLE = no         # Console for debug
# COMMAND_ENABLE = no         # Commands for debug and configuration
# NKRO_ENABLE = yes            # N-Key Rollover
# BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
# AUDIO_ENABLE = no           # Audio output
# RGBLIGHT_ENABLE = no        # Enable WS2812 RGB underlight.
# SWAP_HANDS_ENABLE = no      # Enable one-hand typing
# OLED_ENABLE = no           # OLED display
DYNAMIC_MACRO_ENABLE = yes
# VIA_ENABLE = yes
# RGB_MATRIX_ENABLE = yes
# ENCODER_MAP_ENABLE = no
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes

SRC += num_word.c swapper.c
